[package]
name = "sysprims-proc"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
description = "Process inspection and enumeration utilities"

[dependencies]
sysprims-core.workspace = true
